### ISSUE TITLE
Add support for varying thickness

### ISSUE THREAD

**Issue by bhavyaagg** [coslos/LiveWhiteboard-Website#10]
The user should be able to change the thickness of the stroke maybe by using a slider.

**Comment by JesseKuntz** [comment]
@bhavyaagg just as an update, I combined the text and slider elements into one bootstrap element (which also helps with the compact feel). Once I convert the custom CSS to bootstrap CSS I will let you know. Should be done by some point today.

**Comment by bhavyaagg** [comment]
Great @JesseKuntz . All the best.
