### ISSUE TITLE
Remove unused statements

### ISSUE THREAD

**Issue by bhavyaagg** [coslos/LiveWhiteboard-Website#5]
Remove statements like:
- [ ] Redundant log statements
- [ ] Unused comments

**Comment by bhavyaagg** [comment]
Any contributor can start with removing useless comments from index.html. Some redundant log statements are present through out the project.

**Comment by RavinduHasithanjana** [comment]
Hi I am interested i will start off by removing the unused statments

**Comment by bhavyaagg** [comment]
Hi @RavinduHasithanjana Sure. Although @svwielga4 has created a PR for this. You can check his work or if there are improvements to his code you can send another PR for sure.
